### ISSUE TITLE
Filter blowups

### ISSUE THREAD

**Issue by jamesb93** [madskjeldgaard/guttersynth-sc#1]
Hi both,

this is awesome and I'm having a lot of fun playing with it. I am getting lots of instances where parameter configurations tend to blow up and result in silence. I see there is a reset button on the GUI, however, when I go back to defaults and press reset it doesn't fix it. Not sure if a meat-ware issue or because the internal biquad/filter doesnt reset.

**Comment by jamesb93** [comment]
I've been clicking end then hitting play again which works just fine! Thanks

**Comment by madskjeldgaard** [comment]
Hi James

Yes I'm afraid it's still quite explosive this algorithm even though we've made it a lot less explosive than it was, hah!

The gui you are referring to I assume is the NdefGui which is not part of this project: http://doc.sccode.org/Classes/NdefGui.html

I think pressing `send` might help as well ? 

Best!

**Comment by jamesb93** [comment]
This is super inspirational stuff! Still enjoying it hours later. I am going to have a crack at a max implementation. It all looks pretty clear to me, except I'm not sure about the SlopedSignal stuff. Is that just a smoothed input?

**Comment by madskjeldgaard** [comment]
nice to hear! 

There's already a max implementation which is where we ported it from (most of it is written in Java though): https://github.com/tommmmudd/guttersynthesis

SlopedSignal is a simple filter that smoothens input values (simple interpolaton really) to make sure things don't crunch up. 

best!

**Comment by jamesb93** [comment]
Yep! Love Mudd's work, just think that there is room for something more modern and open (:
